from flask_wtf import FlaskForm
from wtforms import TextAreaField, SelectField, SubmitField
from wtforms.validators import NumberRange, DataRequired, Email
import email_validator
import operator
from erlab_coat.meta import label2description
label2description['shooting_count'] = 'Police Shootings per State'
label2description['state_cumulative_covid_vaccines_one_dose'] = 'Vaccination - State Cumulative One Dose Vaccine Counts'
label2description['state_cumulative_covid_vaccines_two_dose'] = 'Vaccination - State Cumulative Two Dose Vaccine Counts'
label2description['confirmed_count'] = 'Daily Confirmed County Cases'
label2description['death_count'] = 'Daily County Deaths due to COVID-19'
label2description['recovered_count'] = 'Daily County Recoveries from COVID-19'


def fetch_latest_descriptions_for_choices(in_tuples):
    out = [(e[0], label2description[e[0]]) for e in in_tuples]
    return out


class CoatPlotD3Form(FlaskForm):
    x_choices = [
        ('total_population', 'x'),
        ('number_of_men', 'x'),
        ('number_of_women', 'x'),
        ('men_percentage', 'x'),
        ('women_percentage', 'x'),
        ('race_hispanic', 'x'),
        ('race_white', 'x'),
        ('race_black', 'x'),
        ('race_native', 'x'),
        ('race_asian', 'x'),
        ('pacific', 'x'),
        ('voting_age_citizens', 'x'),
        ('census_income_average',
         'x'),
        ('census_income_margin', 'x'),
        ('census_income_per_capita',
         'x'),
        ('census_income_per_capita_margin',
         'x'),
        ('census_poverty', 'x'),
        ('census_child_poverty', 'x'),
        ('professional_job_percentage', 'x'),
        ('service_job_percentage', 'x'),
        ('office_job_percentage', 'x'),
        ('construction_job_percentage', 'x'),
        ('production_job_percentage', 'x'),
        ('commute_drive_percentage', 'x'),
        ('commute_carpool_percentage', 'x'),
        ('commute_transit_percentage', 'x'),
        ('commute_walk_percentage', 'x'),
        ('commute_other_percentage', 'x'),
        ('commute_noneed_percentage', 'x'),
        ('number_of_employed_people', 'x'),
        ('employment_private_percentage', 'x'),
        ('employment_public_percentage', 'x'),
        ('employment_self_percentage', 'x'),
        ('employment_family_percentage', 'x'),
        ('unemployment_percentage', 'x'),
        ('icu_beds', 'x'),
        ('senior_population_percentage',
         'x'),
        ('seniors_per_icubed',
         'x'),
        ('diversity_index', 'x'),
        ('diversity_black_race', 'Diversity Black Race Ratio'),
        ('diversity_native_race', 'Diversity Native Race Ratio'),
        ('diversity_asian_race', 'Diversity Asian Race Ratio'),
        ('diversity_pacific_race', 'Diversity Pacific Islander Race Ratio'),
        ('diversity_two_or_more_races', 'Diversity Two or More Race Combined Ratio'),
        ('diversity_hispanic_race', 'Diversity Hispanic Rce Ratio'),
        ('diversity_white_race', 'Diversity White Race Ratio'),
        ('ALAND_SQMI', 'Land Area in Square Miles'),
        ('AWATER_SQMI', 'Water Area in Square Miles'),
        # ('mean_land_area', 'Average Land Area'),
        # ('mean_land_water', 'Average Water Area'),
        # ('mean_income_mean', 'Average of Average Income'),
        # ('mean_income_median', 'Average of Median Income'),
        # ('mean_income_std', 'Average Income Standard Deviation'),
        ('mortality_rate', 'Mortality Rate'),
        ('min_mortality_rate', 'Minimum Mortality Rate'),
        ('max_mortality_rate', 'Maximum Mortality Rate'),
        ('change_in_mortality_rate', 'Change in Mortality Rate'),
        ('min_change_in_mortality_rate', 'Minimum Change in Mortality Rate'),
        ('max_change_in_mortality_rate', 'Maximum Change in Mortality Rate'),
        ('democrat_percentage', 'Democrat Vote Percentage'),
        ('republican_percentage', 'Republican Vote Percentage'),
        ('other_than_democrat_or_republican_percentage',
         'Votes other than democrat/republican - Percentage'),
        ('population_density', 'Population Density'),
        ('compliance', 'Compliance with the Shelter at Home Criteria'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag0_4',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag18_49',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag5_17',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag50_64',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65_74',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag75_84',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag85p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_agoverall',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag0_4',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag18_49',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag5_17',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag50_64',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65_74',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag75_84',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag85p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_agoverall',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_infleunza_activity_level', 'x'),
        ('state_eating_and_drinking_locations', 'x'),
        ('state_restaurant_worker_population', 'x'),
        ('state_restaurant_employment_percentage', 'x'),
        ('state_restaurants_annual_sale', 'x'),
        ('restaurants_table_service_to_state_contribution',
         'x'),
        ('restaurants_limited_service_to_state_contribution',
         'x'),
        ('google_mobility_retail_and_recreation_percent_change_from_baseline', 'x'),
        ('google_mobility_grocery_and_pharmacy_percent_change_from_baseline', 'x'),
        ('google_mobility_parks_percent_change_from_baseline', 'x'),
        ('google_mobility_transit_stations_percent_change_from_baseline', 'x'),
        ('google_mobility_workplaces_percent_change_from_baseline', 'x'),
        ('google_mobility_residential_percent_change_from_baseline', 'x'),

        ('average_college_total_confirmed_count_cumsum', 'x'),
        ('average_college_medunit_confirmed_count_cumsum', 'x'),

        ('shooting_count', 'x'),

        ('state_cumulative_covid_vaccines_one_dose', 'x'),
        ('state_cumulative_covid_vaccines_two_dose', 'x')

        # - health data
        # ('obesity_change_female_2001_2009', 'x'),
        # ('obesity_change_male_2001_2009', 'x'),
        # ('obesity_prevalence_female_2011', 'x'),
        # ('obesity_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_female_2011', 'x'),
        # ('physical_activity_sufficient_difference_male_2001_2009', 'x'),
        # ('physical_activity_sufficient_difference_female_2001_2009', 'x'),
        # ('life_expectancy_male_2010', 'x'),
        # ('life_expectancy_female_2010', 'x'),
        # ('life_expectancy_difference_1985_2010_male', 'x'),
        # ('life_expectancy_difference_1985_2010_female', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_total_prevalence_sex_male_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_male_2012', 'x'),
        # ('diabetes_control_prevalence_sex_male_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_total_prevalence_sex_female_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_female_2012', 'x'),
        # ('diabetes_control_prevalence_sex_female_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_total_prevalence_sex_both_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_both_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_total_change_sex_male_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_male_1999_2012', 'x'),
        # ('diabetes_control_change_sex_male_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_total_change_sex_female_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_female_1999_2012', 'x'),
        # ('diabetes_control_change_sex_female_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_total_change_sex_both_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_both_1999_2012', 'x'),
        # ('diabetes_control_change_sex_both_1999_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_male_2012', 'x'),
        # ('alcohol_change_type_any_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_male_2005_2012', 'x')

    ]
    x_choices = fetch_latest_descriptions_for_choices(x_choices)
    x_choices.sort(key=operator.itemgetter(1))

    color_choices = [
        ('total_population', 'Total County Population'),
        ('number_of_men', 'Number of Men in the County'),
        ('number_of_women', 'Number of Women in the County'),
        ('men_percentage', 'Percentage of Men in the County'),
        ('women_percentage', 'Percentage of Women in the County'),
        ('race_hispanic', 'Hispanic Race Ratio'),
        ('race_white', 'White Race Ratio'),
        ('race_black', 'Black Race Ratio'),
        ('race_native', 'Native American Race Ratio'),
        ('race_asian', 'Asian Race Ratio'),
        ('pacific', 'Pacific Islander Race Ratio'),
        ('voting_age_citizens', 'Number of Voting-age Citizens in the County'),
        ('census_income_average',
         'Average Income in the County - Based on US Census'),
        ('census_income_margin', 'Income Margin in the County - Based on US Census'),
        ('census_income_per_capita',
         'Average Income per Capita in the County - Based on US Census'),
        ('census_income_per_capita_margin',
         'Income per Capita Margin in the County - Based on US Census'),
        ('census_poverty', 'Poverty'),
        ('census_child_poverty', 'Child Poverty'),
        ('professional_job_percentage', 'Professional Job Percentage'),
        ('service_job_percentage', 'Service Job Percentage'),
        ('office_job_percentage', 'Office Job Percentage'),
        ('construction_job_percentage', 'Construction Job Percentage'),
        ('production_job_percentage', 'Production Job Percentage'),
        ('commute_drive_percentage', 'Commute to Work: Drive (Percentage)'),
        ('commute_carpool_percentage', 'Commute to Work: Carpool (Percentage)'),
        ('commute_transit_percentage', 'Commute to Work: Transit (Percentage)'),
        ('commute_walk_percentage', 'Commute to Work: Walk (Percentage)'),
        ('commute_other_percentage', 'Commute to Work: Other (Percentage)'),
        ('commute_noneed_percentage', 'Commute to Work: Work at Home (Percentage)'),
        ('number_of_employed_people', 'Number of Employed People in County'),
        ('employment_private_percentage', 'Private Employment'),
        ('employment_public_percentage', 'Public Employment Percentage'),
        ('employment_self_percentage', 'Self Employment Percentage'),
        ('employment_family_percentage', 'Family Employment Percentage'),
        ('unemployment_percentage', 'Unemployment Percentage'),
        ('icu_beds', 'Number of ICU Beds'),
        ('senior_population_percentage',
         'Senior (above 60 years old) population percentage'),
        ('seniors_per_icubed',
         'Senior (above 60 years old) per each ICU bed'),
        ('diversity_index', 'Diversity Index'),
        ('diversity_black_race', 'Diversity Black Race Ratio'),
        ('diversity_native_race', 'Diversity Native Race Ratio'),
        ('diversity_asian_race', 'Diversity Asian Race Ratio'),
        ('diversity_pacific_race', 'Diversity Pacific Islander Race Ratio'),
        ('diversity_two_or_more_races', 'Diversity Two or More Race Combined Ratio'),
        ('diversity_hispanic_race', 'Diversity Hispanic Rce Ratio'),
        ('diversity_white_race', 'Diversity White Race Ratio'),
        ('ALAND_SQMI', 'Land Area in Square Miles'),
        ('AWATER_SQMI', 'Water Area in Square Miles'),
        # ('mean_land_area', 'Average Land Area'),
        # ('mean_land_water', 'Average Water Area'),
        # ('mean_income_mean', 'Average of Average Income'),
        # ('mean_income_median', 'Average of Median Income'),
        # ('mean_income_std', 'Average'),
        ('mortality_rate', 'Mortality Rate'),
        ('min_mortality_rate', 'Minimum Mortality Rate'),
        ('max_mortality_rate', 'Maximum Mortality Rate'),
        ('change_in_mortality_rate', 'Change in Mortality Rate'),
        ('min_change_in_mortality_rate', 'Minimum Change in Mortality Rate'),
        ('max_change_in_mortality_rate', 'Maximum Change in Mortality Rate'),
        ('democrat_percentage', 'Democrat Vote Percentage'),
        ('republican_percentage', 'Republican Vote Percentage'),
        ('other_than_democrat_or_republican_percentage',
         'Votes other than democrat/republican - Percentage'),
        ('population_density', 'Population Density'),
        ('compliance', 'Compliance with the Shelter at Home Criteria'),
        ('confirmed_count_cumsum_per100k', 'Population Normalized Cases to Date'),
        ('death_count_cumsum_per100k', 'Population Normalized Deaths to Date'),
        ('recovered_count_cumsum_per100k', 'x'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag0_4',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag18_49',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag5_17',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag50_64',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65_74',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag75_84',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag85p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_agoverall',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag0_4',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag18_49',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag5_17',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag50_64',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65_74',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag75_84',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag85p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_agoverall',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_infleunza_activity_level', 'State Reported Influenza Activity Level - Survey'),
        ('state_eating_and_drinking_locations', 'Number of Eating/Drinking Locations in the State'),
        ('state_restaurant_worker_population', 'Number of Restaurant Workers in the State'),
        ('state_restaurant_employment_percentage', 'Percentage of Restaurant Work in State Employment'),
        ('state_restaurants_annual_sale', 'State Annual Restaurant Sale'),
        ('restaurants_table_service_to_state_contribution',
         'Contribution to State Economy from Every Dollar Spent on Restaurant - Table Services'),
        ('restaurants_limited_service_to_state_contribution',
         'Contribution to State Economy from Every Dollar Spent on Restaurant - Limited Services'),
        ('google_mobility_retail_and_recreation_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Retail and Recreation'),
        ('google_mobility_grocery_and_pharmacy_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Grocery and Pharmacy'),
        ('google_mobility_parks_percent_change_from_baseline', 'Changes in Mobility From Baseline - Transit Stations'),
        ('google_mobility_transit_stations_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Workplaces'),
        ('google_mobility_workplaces_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Retail and Recreation'),
        ('google_mobility_residential_percent_change_from_baseline', 'Changes in Mobility From Baseline - Residential'),
        ('average_college_total_confirmed_count_cumsum', 'x'),
        ('average_college_medunit_confirmed_count_cumsum', 'x'),

        ('shooting_count', 'x'),
        ('state_cumulative_covid_vaccines_one_dose', 'x'),
        ('state_cumulative_covid_vaccines_two_dose', 'x')
        # ('obesity_change_female_2001_2009', 'x'),
        # ('obesity_change_male_2001_2009', 'x'),
        # ('obesity_prevalence_female_2011', 'x'),
        # ('obesity_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_female_2011', 'x'),
        # ('physical_activity_sufficient_difference_male_2001_2009', 'x'),
        # ('physical_activity_sufficient_difference_female_2001_2009', 'x'),
        # ('life_expectancy_male_2010', 'x'),
        # ('life_expectancy_female_2010', 'x'),
        # ('life_expectancy_difference_1985_2010_male', 'x'),
        # ('life_expectancy_difference_1985_2010_female', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_total_prevalence_sex_male_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_male_2012', 'x'),
        # ('diabetes_control_prevalence_sex_male_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_total_prevalence_sex_female_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_female_2012', 'x'),
        # ('diabetes_control_prevalence_sex_female_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_total_prevalence_sex_both_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_both_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_total_change_sex_male_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_male_1999_2012', 'x'),
        # ('diabetes_control_change_sex_male_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_total_change_sex_female_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_female_1999_2012', 'x'),
        # ('diabetes_control_change_sex_female_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_total_change_sex_both_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_both_1999_2012', 'x'),
        # ('diabetes_control_change_sex_both_1999_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_male_2012', 'x'),
        # ('alcohol_change_type_any_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_male_2005_2012', 'x')
    ]
    color_choices = fetch_latest_descriptions_for_choices(color_choices)
    color_choices.sort(key=operator.itemgetter(1))

    size_choices = [
        ('total_population', 'Total County Population'),
        ('number_of_men', 'Number of Men in the County'),
        ('number_of_women', 'Number of Women in the County'),
        ('men_percentage', 'Percentage of Men in the County'),
        ('women_percentage', 'Percentage of Women in the County'),
        ('race_hispanic', 'Hispanic Race Ratio'),
        ('race_white', 'White Race Ratio'),
        ('race_black', 'Black Race Ratio'),
        ('race_native', 'Native American Race Ratio'),
        ('race_asian', 'Asian Race Ratio'),
        ('pacific', 'Pacific Islander Race Ratio'),
        ('voting_age_citizens', 'Number of Voting-age Citizens in the County'),
        ('census_income_average',
         'Average Income in the County - Based on US Census'),
        ('census_income_margin', 'Income Margin in the County - Based on US Census'),
        ('census_income_per_capita',
         'Average Income per Capita in the County - Based on US Census'),
        ('census_income_per_capita_margin',
         'Income per Capita Margin in the County - Based on US Census'),
        ('census_poverty', 'Poverty'),
        ('census_child_poverty', 'Child Poverty'),
        ('professional_job_percentage', 'Professional Job Percentage'),
        ('service_job_percentage', 'Service Job Percentage'),
        ('office_job_percentage', 'Office Job Percentage'),
        ('construction_job_percentage', 'Construction Job Percentage'),
        ('production_job_percentage', 'Production Job Percentage'),
        ('commute_drive_percentage', 'Commute to Work: Drive (Percentage)'),
        ('commute_carpool_percentage', 'Commute to Work: Carpool (Percentage)'),
        ('commute_transit_percentage', 'Commute to Work: Transit (Percentage)'),
        ('commute_walk_percentage', 'Commute to Work: Walk (Percentage)'),
        ('commute_other_percentage', 'Commute to Work: Other (Percentage)'),
        ('commute_noneed_percentage', 'Commute to Work: Work at Home (Percentage)'),
        ('number_of_employed_people', 'Number of Employed People in County'),
        ('employment_private_percentage', 'Private Employment'),
        ('employment_public_percentage', 'Public Employment Percentage'),
        ('employment_self_percentage', 'Self Employment Percentage'),
        ('employment_family_percentage', 'Family Employment Percentage'),
        ('unemployment_percentage', 'Unemployment Percentage'),
        ('icu_beds', 'Number of ICU Beds'),
        ('senior_population_percentage',
         'Senior (above 60 years old) population percentage'),
        ('seniors_per_icubed',
         'Senior (above 60 years old) per each ICU bed'),
        ('diversity_index', 'Diversity Index'),
        ('diversity_black_race', 'Diversity Black Race Ratio'),
        ('diversity_native_race', 'Diversity Native Race Ratio'),
        ('diversity_asian_race', 'Diversity Asian Race Ratio'),
        ('diversity_pacific_race', 'Diversity Pacific Islander Race Ratio'),
        ('diversity_two_or_more_races', 'Diversity Two or More Race Combined Ratio'),
        ('diversity_hispanic_race', 'Diversity Hispanic Rce Ratio'),
        ('diversity_white_race', 'Diversity White Race Ratio'),
        ('ALAND_SQMI', 'Land Area in Square Miles'),
        ('AWATER_SQMI', 'Water Area in Square Miles'),
        # ('mean_land_area', 'Average Land Area'),
        # ('mean_land_water', 'Average Water Area'),
        # ('mean_income_mean', 'Average of Average Income'),
        # ('mean_income_median', 'Average of Median Income'),
        # ('mean_income_std', 'Average'),
        ('mortality_rate', 'Mortality Rate'),
        ('min_mortality_rate', 'Minimum Mortality Rate'),
        ('max_mortality_rate', 'Maximum Mortality Rate'),
        ('change_in_mortality_rate', 'Change in Mortality Rate'),
        ('min_change_in_mortality_rate', 'Minimum Change in Mortality Rate'),
        ('max_change_in_mortality_rate', 'Maximum Change in Mortality Rate'),
        ('democrat_percentage', 'Democrat Vote Percentage'),
        ('republican_percentage', 'Republican Vote Percentage'),
        ('other_than_democrat_or_republican_percentage',
         'Votes other than democrat/republican - Percentage'),
        ('population_density', 'Population Density'),
        ('compliance', 'Compliance with the Shelter at Home Criteria'),
        ('confirmed_count_cumsum_per100k', 'Population Normalized Cases to Date'),
        ('death_count_cumsum_per100k', 'Population Normalized Deaths to Date'),
        ('recovered_count_cumsum_per100k', 'x'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag0_4',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag18_49',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag5_17',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag50_64',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag65_74',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag75_84',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_ag85p',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_cumulative_covid_hospitalization_rate_per_100k_agoverall',
         'State Cumulative Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag0_4',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 0-4'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag18_49',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 18-49'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag5_17',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 5-17'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag50_64',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 50-64'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag65_74',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 65-74'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag75_84',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 75-84'),
        ('state_weekly_covid_hospitalization_rate_per_100k_ag85p',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: 85+'),
        ('state_weekly_covid_hospitalization_rate_per_100k_agoverall',
         'State Weekly Lab Confirmed COVID-19 Hospitalization per 100,000 people - Age: Overall'),
        ('state_infleunza_activity_level', 'State Reported Influenza Activity Level - Survey'),
        ('state_eating_and_drinking_locations', 'Number of Eating/Drinking Locations in the State'),
        ('state_restaurant_worker_population', 'Number of Restaurant Workers in the State'),
        ('state_restaurant_employment_percentage', 'Percentage of Restaurant Work in State Employment'),
        ('state_restaurants_annual_sale', 'State Annual Restaurant Sale'),
        ('restaurants_table_service_to_state_contribution',
         'Contribution to State Economy from Every Dollar Spent on Restaurant - Table Services'),
        ('restaurants_limited_service_to_state_contribution',
         'Contribution to State Economy from Every Dollar Spent on Restaurant - Limited Services'),
        ('google_mobility_retail_and_recreation_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Retail and Recreation'),
        ('google_mobility_grocery_and_pharmacy_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Grocery and Pharmacy'),
        ('google_mobility_parks_percent_change_from_baseline', 'Changes in Mobility From Baseline - Transit Stations'),
        ('google_mobility_transit_stations_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Workplaces'),
        ('google_mobility_workplaces_percent_change_from_baseline',
         'Changes in Mobility From Baseline - Retail and Recreation'),
        ('google_mobility_residential_percent_change_from_baseline', 'Changes in Mobility From Baseline - Residential'),
        ('average_college_total_confirmed_count_cumsum', 'x'),
        ('average_college_medunit_confirmed_count_cumsum', 'x'),

        ('shooting_count', 'x'),

        ('state_cumulative_covid_vaccines_one_dose', 'x'),
        ('state_cumulative_covid_vaccines_two_dose', 'x')
        # ('obesity_change_female_2001_2009', 'x'),
        # ('obesity_change_male_2001_2009', 'x'),
        # ('obesity_prevalence_female_2011', 'x'),
        # ('obesity_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_male_2011', 'x'),
        # ('physical_activity_sufficient_prevalence_female_2011', 'x'),
        # ('physical_activity_sufficient_difference_male_2001_2009', 'x'),
        # ('physical_activity_sufficient_difference_female_2001_2009', 'x'),
        # ('life_expectancy_male_2010', 'x'),
        # ('life_expectancy_female_2010', 'x'),
        # ('life_expectancy_difference_1985_2010_male', 'x'),
        # ('life_expectancy_difference_1985_2010_female', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_male_2012', 'x'),
        # ('diabetes_total_prevalence_sex_male_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_male_2012', 'x'),
        # ('diabetes_control_prevalence_sex_male_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_female_2012', 'x'),
        # ('diabetes_total_prevalence_sex_female_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_female_2012', 'x'),
        # ('diabetes_control_prevalence_sex_female_2012', 'x'),
        # ('diabetes_diagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_undiagnosed_prevalence_sex_both_2012', 'x'),
        # ('diabetes_total_prevalence_sex_both_2012', 'x'),
        # ('diabetes_awareness_prevalence_sex_both_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_male_1999_2012', 'x'),
        # ('diabetes_total_change_sex_male_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_male_1999_2012', 'x'),
        # ('diabetes_control_change_sex_male_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_female_1999_2012', 'x'),
        # ('diabetes_total_change_sex_female_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_female_1999_2012', 'x'),
        # ('diabetes_control_change_sex_female_1999_2012', 'x'),
        # ('diabetes_diagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_undiagnosed_change_sex_both_1999_2012', 'x'),
        # ('diabetes_total_change_sex_both_1999_2012', 'x'),
        # ('diabetes_awareness_change_sex_both_1999_2012', 'x'),
        # ('diabetes_control_change_sex_both_1999_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_both_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_female_2012', 'x'),
        # ('alcohol_prevalence_type_any_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_heavy_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_binge_sex_male_2012', 'x'),
        # ('alcohol_prevalence_type_prop_heavy_sex_male_2012', 'x'),
        # ('alcohol_change_type_any_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_both_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_female_2005_2012', 'x'),
        # ('alcohol_change_type_any_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_binge_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_heavy_sex_male_2005_2012', 'x'),
        # ('alcohol_change_type_prop_binge_sex_male_2005_2012', 'x')
    ]
    size_choices = fetch_latest_descriptions_for_choices(size_choices)
    size_choices.sort(key=operator.itemgetter(1))

    y_choices = [
        ('confirmed_count_cumsum_per100k', 'Cumulative Confirmed COVID-19 Cases per 100,000'),
        ('death_count_cumsum_per100k', 'Cumulative Deaths due to COVID-19 per 100,000'),
        ('recovered_count_cumsum_per100k', 'Cumulative Recoveries from COVID-19 per 100,000'),
        ('confirmed_count_cumsum', 'Cumulative Confirmed COVID-19 Cases'),
        ('death_count_cumsum', 'Cumulative Deaths due to COVID-19'),
        ('recovered_count_cumsum', 'Cumulative Recoveries from COVID-19'),
        ('confirmed_count', 'Daily Confirmed COVID-19 Cases'),
        ('death_count', 'Daily Deaths due to COVID-19'),
        ('recovered_count', 'Daily Recoveries from COVID-19'),
    ]
    y_choices = fetch_latest_descriptions_for_choices(y_choices)
    y_choices.sort(key=operator.itemgetter(1))

    x_var = SelectField('X - Axis', default='commute_drive_percentage', choices=x_choices)
    color_var = SelectField('Datapoint Color', choices=color_choices, default='icu_beds')
    size_var = SelectField('Datapoint Size', choices=size_choices, default='total_population')
    y_var = SelectField('Y - Axis', choices=y_choices, default='max_confirmed_count')

    show_labels = SelectField('Region Labels', choices=[
        ('show', 'Location'),
        ('dont_show', 'None')
    ], default='dont_show')

    resolution = SelectField('Resolution', choices=[
        ('state', 'States'),
        ('counties', 'Counties')
    ])

    county_filter = TextAreaField('County Filter [Example: Los Angeles,Alameda]', validators=[])
    state_filter = TextAreaField('State Filter [Example: NY,NJ]', validators=[])

    submit = SubmitField('Plot')

    def validate(self):
        if not super(CoatPlotD3Form, self).validate():
            return False

        if (self.county_filter.data == '') and (self.state_filter.data == '') and (self.resolution.data == 'counties'):
            self.county_filter.errors = ["Monitoring all counties across all times results in too much data to handle by the browsers. Please provide a filter."]
            return False

        if (self.x_var.data == self.color_var.data) and (self.color_var.data == self.size_var.data):
            self.x_var.errors += ["This choice cannot be the same as two other choices."]
            self.color_var.errors += ["This choice cannot be the same as two other choices."]
            self.size_var.errors += ["This choice cannot be the same as two other choices."]
            return False

        if (self.resolution.data == 'state') and not (self.county_filter.data == ''):
            self.county_filter.errors = ["You cannot set county filters when the resolution is state-level."]
            return False

        return True
