"""empty message

Revision ID: 70390976b144
Revises: 9d0b13430a9f
Create Date: 2020-05-29 14:26:58.296307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70390976b144'
down_revision = '9d0b13430a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('alcohol_prevalence_type_any_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_heavy_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_binge_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_heavy_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_binge_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_any_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_heavy_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_binge_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_heavy_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_binge_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_any_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_heavy_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_binge_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_binge_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_prevalence_type_prop_heavy_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_any_sex_both_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_heavy_sex_both_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_binge_sex_both_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_heavy_sex_both_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_binge_sex_both_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_any_sex_female_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_heavy_sex_female_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_binge_sex_female_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_heavy_sex_female_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_binge_sex_female_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_any_sex_male_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_heavy_sex_male_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_binge_sex_male_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_heavy_sex_male_2005_2012', sa.Float(), nullable=True),
    sa.Column('alcohol_change_type_prop_binge_sex_male_2005_2012', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcohol_state'), 'alcohol', ['state'], unique=False)
    op.create_index('myindex_alcohol', 'alcohol', ['county', 'state'], unique=True)
    op.create_table('diabetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('diabetes_diagnosed_prevalence_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_prevalence_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_prevalence_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_prevalence_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_prevalence_sex_male_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_diagnosed_prevalence_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_prevalence_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_prevalence_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_prevalence_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_prevalence_sex_female_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_diagnosed_prevalence_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_prevalence_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_prevalence_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_prevalence_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_prevalence_sex_both_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_diagnosed_change_sex_male_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_change_sex_male_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_change_sex_male_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_change_sex_male_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_change_sex_male_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_diagnosed_change_sex_female_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_change_sex_female_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_change_sex_female_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_change_sex_female_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_change_sex_female_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_diagnosed_change_sex_both_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_undiagnosed_change_sex_both_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_total_change_sex_both_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_awareness_change_sex_both_1999_2012', sa.Float(), nullable=True),
    sa.Column('diabetes_control_change_sex_both_1999_2012', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetes_state'), 'diabetes', ['state'], unique=False)
    op.create_index('myindex_diabetes', 'diabetes', ['county', 'state'], unique=True)
    op.create_table('obesity_and_life',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('obesity_change_female_2001_2009', sa.Float(), nullable=True),
    sa.Column('obesity_change_male_2001_2009', sa.Float(), nullable=True),
    sa.Column('obesity_prevalence_female_2011', sa.Float(), nullable=True),
    sa.Column('obesity_prevalence_male_2011', sa.Float(), nullable=True),
    sa.Column('physical_activity_sufficient_prevalence_male_2011', sa.Float(), nullable=True),
    sa.Column('physical_activity_sufficient_prevalence_female_2011', sa.Float(), nullable=True),
    sa.Column('physical_activity_sufficient_difference_male_2001_2009', sa.Float(), nullable=True),
    sa.Column('physical_activity_sufficient_difference_female_2001_2009', sa.Float(), nullable=True),
    sa.Column('life_expectancy_male_2010', sa.Float(), nullable=True),
    sa.Column('life_expectancy_female_2010', sa.Float(), nullable=True),
    sa.Column('life_expectancy_difference_1985_2010_male', sa.Float(), nullable=True),
    sa.Column('life_expectancy_difference_1985_2010_female', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obesity_and_life_state'), 'obesity_and_life', ['state'], unique=False)
    op.create_index('myindex_obesity', 'obesity_and_life', ['county', 'state'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('myindex_obesity', table_name='obesity_and_life')
    op.drop_index(op.f('ix_obesity_and_life_state'), table_name='obesity_and_life')
    op.drop_table('obesity_and_life')
    op.drop_index('myindex_diabetes', table_name='diabetes')
    op.drop_index(op.f('ix_diabetes_state'), table_name='diabetes')
    op.drop_table('diabetes')
    op.drop_index('myindex_alcohol', table_name='alcohol')
    op.drop_index(op.f('ix_alcohol_state'), table_name='alcohol')
    op.drop_table('alcohol')
    # ### end Alembic commands ###
