"""empty message

Revision ID: 8b6fd1aeb572
Revises: f8387ee5852a
Create Date: 2021-03-11 12:55:17.463774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6fd1aeb572'
down_revision = 'f8387ee5852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_cumulative_covid_vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('state_cumulative_covid_vaccines_one_dose', sa.Float(), nullable=True),
    sa.Column('state_cumulative_covid_vaccines_two_dose', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_cumulative_covid_vaccines')
    # ### end Alembic commands ###
