"""empty message

Revision ID: f8387ee5852a
Revises: 99cc0c813389
Create Date: 2021-03-02 23:50:03.842011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8387ee5852a'
down_revision = '99cc0c813389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_shooting_per_month', sa.Column('confirmed_date', sa.DateTime(), nullable=True))
    op.drop_column('police_shooting_per_month', 'date')
    op.add_column('tweet_table_1', sa.Column('confirmed_date', sa.DateTime(), nullable=True))
    op.drop_column('tweet_table_1', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet_table_1', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tweet_table_1', 'confirmed_date')
    op.add_column('police_shooting_per_month', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('police_shooting_per_month', 'confirmed_date')
    # ### end Alembic commands ###
